#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("conseilMoi.Resource", IsApplication=true)]

namespace conseilMoi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::conseilMoi.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::conseilMoi.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::conseilMoi.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_custom_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Historique = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconeTest = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Profil = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Scan = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Suggestions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Synthese = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int button1 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int button2 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int button3 = 2131230749;
			
			// aapt resource value: 0x7f080004
			public const int buttonMajBase = 2131230724;
			
			// aapt resource value: 0x7f08002e
			public const int contentFrame = 2131230766;
			
			// aapt resource value: 0x7f08000a
			public const int imageViewAvertissementAvertissement = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int imageViewAvertissementConseil = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int imageViewAvertissementHistorique = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int imageViewAvertissementProfil = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int imageViewAvertissementScann = 2131230728;
			
			// aapt resource value: 0x7f080012
			public const int imageViewConseilAvertissement = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int imageViewConseilConseil = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int imageViewConseilHistorique = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int imageViewConseilProfil = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int imageViewConseilScann = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int imageViewHistoriqueAvertissement = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int imageViewHistoriqueConseil = 2131230744;
			
			// aapt resource value: 0x7f080016
			public const int imageViewHistoriqueHistorique = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int imageViewHistoriqueProfil = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int imageViewHistoriqueScann = 2131230743;
			
			// aapt resource value: 0x7f080025
			public const int imageViewProduitAvertissement = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int imageViewProduitConseil = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int imageViewProduitHistorique = 2131230754;
			
			// aapt resource value: 0x7f080021
			public const int imageViewProduitProfil = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int imageViewProduitScann = 2131230755;
			
			// aapt resource value: 0x7f08002d
			public const int imageViewProfilAvertissement = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int imageViewProfilConseil = 2131230764;
			
			// aapt resource value: 0x7f08002a
			public const int imageViewProfilHistorique = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int imageViewProfilProfil = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int imageViewProfilScann = 2131230763;
			
			// aapt resource value: 0x7f08001a
			public const int linearLayout1 = 2131230746;
			
			// aapt resource value: 0x7f080027
			public const int linearLayoutBilanDesCirters = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int linearLayoutProfile = 2131230758;
			
			// aapt resource value: 0x7f080005
			public const int menuAvertissement = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int menuAvertissementProduit = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int menuConseil = 2131230733;
			
			// aapt resource value: 0x7f080014
			public const int menuHistorique = 2131230740;
			
			// aapt resource value: 0x7f08001e
			public const int menuProduitInfos = 2131230750;
			
			// aapt resource value: 0x7f080028
			public const int menuProfil = 2131230760;
			
			// aapt resource value: 0x7f08000b
			public const int textView1 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int textView2 = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int textViewAvertissementTexte = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int textViewAvertissementTitre = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int textViewHistoriqueTitre = 2131230739;
			
			// aapt resource value: 0x7f08001f
			public const int textViewIdProduit = 2131230751;
			
			// aapt resource value: 0x7f080003
			public const int textViewIdProduitAv = 2131230723;
			
			// aapt resource value: 0x7f080020
			public const int textViewInfoScan = 2131230752;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Avertissement = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Conseil = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Historique = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Produit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profil = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int data = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
